site_name: Observability Playbook Docs
site_url: https://luisjguedes.github.io/observability-playbook-docs/
repo_url: https://github.com/luisjguedes/observability-playbook-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
nav:
  - Home: index.md
  - Playbook: observability-playbook.md
  - Contributing:
      - Style guide: contributing/style-guide.md
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
