name: Vale (style checks)

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - ".vale.ini"
      - "styles/**"
  push:
    branches: ["main"]
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - ".vale.ini"
      - "styles/**"
  workflow_dispatch:

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 3.7.1
          files: docs/**/*.md README.md contributing/**/*.md
            **/*.md
            **/*.mdx
          reporter: local
          filter_mode: nofilter
          fail_on_error: false
          level: warning
