name: Vale (style checks)

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 3.7.1
          files: .
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: true
