name: Vale (style checks)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional but useful: ensures styles are fetched consistently
      - name: Vale (style checks)
        continue-on-error: true
        uses: errata-ai/vale-action@v2
        with:
          version: 3.7.1
          files: .
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: false
          level: warning
          token: ${{ secrets.GITHUB_TOKEN }}
